version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Installing dependencies...
      - pip install --upgrade pip huggingface_hub
      - echo Creating models directory...
      - mkdir -p models
      - echo Downloading model...
      - python3 download_model.py
      - echo DEBUG - Environment variables:
      - echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - echo AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
      - echo IMAGE_REPO_URI=$IMAGE_REPO_URI
      - echo Verifying model download...
      - ls -la models/
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - docker build -t my-llm-docker .
      - echo Copying model into the built image...
      - docker run --name temp-container my-llm-docker:latest /bin/true
      - docker cp models/M-MOE-4X7B-Dark-MultiVerse-UC-E32-24B-D_AU-Q4_k_m.gguf temp-container:/app/models/
      - docker commit temp-container my-llm-docker:latest
      - docker rm temp-container
      - echo Tagging with URI $IMAGE_REPO_URI:latest
      - docker tag my-llm-docker:latest $IMAGE_REPO_URI:latest
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"my-llm-container","imageUri":"%s"}]' $IMAGE_REPO_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json